### ISSUE TITLE
Dropdowns - Incompatible units: 'rem' and 'px' 

### ISSUE THREAD

**Issue by pfoedermayr** [telerik/kendo-theme-default#397]
After updating `kendo-theme-default` (from `2.28.0` to `2.28.1`) the error `Incompatible units: 'rem' and 'px'` is thrown on webpack-build.

This does only happen when using it together with `kendo-theme-bootstrap`.

As a workaround setting `$padding-x` manually works. 

### Excerpt from the scss-file
````
...
// $padding-x: 8px; // Workaround: Incompatible units: 'rem' and 'px'
@import "~bootstrap/scss/bootstrap";
@import "~@progress/kendo-theme-bootstrap/scss/all";
...
````

### Complete error:
````
Incompatible units: 'rem' and 'px'.
in <path>\node_modules\@progress\kendo-theme-default\scss\combobox\_layout.scss (line 44, column 28)
at runLoaders (<path>\node_modules\webpack\lib\NormalModule.js:192:19)
at <path>\node_modules\loader-runner\lib\LoaderRunner.js:364:11
at <path>\node_modules\loader-runner\lib\LoaderRunner.js:230:18
at context.callback (<path>\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
at Object.asyncSassJobQueue.push [as callback] (<path>\node_modules\sass-loader\lib\loader.js:57:13)
at Object.<anonymous> (<path>\node_modules\sass-loader\node_modules\async\dist\async.js:2262:31)
at apply (<path>\node_modules\sass-loader\node_modules\async\dist\async.js:20:25)
at Object.<anonymous> (<path>\node_modules\sass-loader\node_modules\async\dist\async.js:56:12)
at Object.callback (<path>\node_modules\sass-loader\node_modules\async\dist\async.js:944:16)
at options.error (<path>\node_modules\node-sass\lib\index.js:294:32)
````
### Used versions:
kendo-theme-default: 2.28.1
kendo-theme-bootstrap: 2.0.0-beta.5

Not sure if that's related to the default-theme or the bootstrap-theme,
I reported it here because it popped up after updating the default-theme.

**Comment by inikolova** [comment]
Thank you for reporting this issue -> I have just pushed a fix for it:
https://github.com/telerik/kendo-theme-default/commit/874e20b883896cd408c222cebb0b2945be3272f2

**Comment by pfoedermayr** [comment]
Thank you!
